from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect,
                            Qt)
from PySide6.QtGui import (QFont)
from PySide6.QtWidgets import (QCheckBox, QComboBox, QDoubleSpinBox,
                               QFrame, QLabel, QLineEdit, QProgressBar, QPushButton, QSpinBox,
                               QStackedWidget, QStatusBar, QVBoxLayout, QWidget)


class UiMainWindow(object):
    def __init__(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 771, 581))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setFrameShape(QFrame.Shape.NoFrame)
        self.stackedWidget.setLineWidth(0)
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.verticalLayoutWidget = QWidget(self.page_1)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 70, 721, 441))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(u"label_2")

        self.verticalLayout.addWidget(self.label_2)

        self.pushButton = QPushButton(self.page_1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(620, 30, 111, 29))
        self.pushButton_2 = QPushButton(self.page_1)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QRect(560, 520, 171, 29))
        self.lineEdit = QLineEdit(self.page_1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 591, 28))
        self.label = QLabel(self.page_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 413, 20))
        font = QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 10, 413, 20))
        font1 = QFont()
        font1.setBold(False)
        font1.setUnderline(True)
        font1.setKerning(True)
        self.label_6.setFont(font1)
        self.label_6.setFrameShape(QFrame.Shape.NoFrame)
        self.pushButton_5 = QPushButton(self.page_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QRect(560, 520, 171, 29))
        self.pushButton_6 = QPushButton(self.page_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QRect(10, 520, 171, 29))
        self.spinBox_3 = QSpinBox(self.page_2)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(77, 130, 71, 29))
        self.spinBox_3.setValue(64)
        self.label_8 = QLabel(self.page_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 40, 161, 20))
        font2 = QFont()
        font2.setBold(True)
        font2.setItalic(True)
        self.label_8.setFont(font2)
        self.label_8.setAutoFillBackground(False)
        self.label_9 = QLabel(self.page_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 70, 231, 20))
        self.label_9.setFont(font2)
        self.label_10 = QLabel(self.page_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 100, 413, 20))
        self.label_10.setFont(font2)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setScaledContents(False)
        self.label_11 = QLabel(self.page_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 130, 61, 20))
        self.label_12 = QLabel(self.page_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(170, 130, 131, 20))
        self.comboBox = QComboBox(self.page_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(280, 130, 201, 28))
        self.doubleSpinBox = QDoubleSpinBox(self.page_2)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(600, 130, 131, 29))
        self.doubleSpinBox.setDecimals(5)
        self.doubleSpinBox.setMaximum(1.000000000000000)
        self.doubleSpinBox.setSingleStep(0.000010000000000)
        self.doubleSpinBox.setValue(0.000100000000000)
        self.label_14 = QLabel(self.page_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 170, 531, 20))
        self.label_14.setFont(font2)
        self.checkBox = QCheckBox(self.page_2)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(80, 200, 93, 26))
        self.checkBox.setChecked(False)
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 240, 161, 20))
        self.label_15.setFont(font2)
        self.label_16 = QLabel(self.page_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 270, 61, 20))
        self.spinBox_4 = QSpinBox(self.page_2)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(77, 270, 71, 29))
        self.spinBox_4.setValue(32)
        self.label_17 = QLabel(self.page_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(170, 270, 131, 20))
        self.comboBox_2 = QComboBox(self.page_2)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(280, 270, 201, 28))
        self.doubleSpinBox_2 = QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(600, 270, 131, 29))
        self.doubleSpinBox_2.setDecimals(5)
        self.doubleSpinBox_2.setMaximum(1.000000000000000)
        self.doubleSpinBox_2.setSingleStep(0.000010000000000)
        self.doubleSpinBox_2.setValue(0.000100000000000)
        self.label_19 = QLabel(self.page_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 320, 161, 20))
        self.label_19.setFont(font2)
        self.label_20 = QLabel(self.page_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 350, 61, 20))
        self.spinBox_5 = QSpinBox(self.page_2)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(77, 350, 71, 29))
        self.spinBox_5.setValue(16)
        self.label_21 = QLabel(self.page_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(170, 350, 131, 20))
        self.comboBox_3 = QComboBox(self.page_2)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(280, 350, 201, 28))
        self.doubleSpinBox_3 = QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(600, 350, 131, 29))
        self.doubleSpinBox_3.setDecimals(5)
        self.doubleSpinBox_3.setMaximum(1.000000000000000)
        self.doubleSpinBox_3.setSingleStep(0.000010000000000)
        self.doubleSpinBox_3.setValue(0.000100000000000)
        self.label_23 = QLabel(self.page_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 390, 171, 20))
        self.label_23.setFont(font2)
        self.label_24 = QLabel(self.page_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 420, 61, 20))
        self.spinBox_6 = QSpinBox(self.page_2)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(77, 420, 71, 29))
        self.spinBox_6.setReadOnly(True)
        self.spinBox_6.setValue(1)
        self.label_25 = QLabel(self.page_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(170, 420, 131, 20))
        self.comboBox_4 = QComboBox(self.page_2)
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(280, 420, 201, 28))
        self.doubleSpinBox_4 = QDoubleSpinBox(self.page_2)
        self.doubleSpinBox_4.setObjectName(u"doubleSpinBox_4")
        self.doubleSpinBox_4.setGeometry(QRect(600, 420, 131, 29))
        self.doubleSpinBox_4.setDecimals(5)
        self.doubleSpinBox_4.setMaximum(1.000000000000000)
        self.doubleSpinBox_4.setSingleStep(0.000010000000000)
        self.doubleSpinBox_4.setValue(0.000100000000000)
        self.label_29 = QLabel(self.page_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(500, 130, 111, 20))
        self.label_30 = QLabel(self.page_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(500, 270, 111, 20))
        self.label_31 = QLabel(self.page_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(500, 350, 111, 20))
        self.label_32 = QLabel(self.page_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(500, 420, 111, 20))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_7 = QLabel(self.page_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 413, 20))
        self.label_7.setFont(font)
        self.pushButton_7 = QPushButton(self.page_3)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QRect(10, 520, 171, 29))
        self.pushButton_8 = QPushButton(self.page_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QRect(300, 40, 171, 61))
        self.progressBar = QProgressBar(self.page_3)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(180, 160, 421, 23))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar_2 = QProgressBar(self.page_3)
        self.progressBar_2.setObjectName(u"progressBar_2")
        self.progressBar_2.setGeometry(QRect(180, 250, 421, 23))
        self.progressBar_2.setValue(0)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setOrientation(Qt.Orientation.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_3 = QProgressBar(self.page_3)
        self.progressBar_3.setObjectName(u"progressBar_3")
        self.progressBar_3.setGeometry(QRect(180, 340, 421, 23))
        self.progressBar_3.setValue(0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setOrientation(Qt.Orientation.Horizontal)
        self.progressBar_3.setInvertedAppearance(False)
        self.progressBar_4 = QProgressBar(self.page_3)
        self.progressBar_4.setObjectName(u"progressBar_4")
        self.progressBar_4.setGeometry(QRect(180, 430, 421, 23))
        self.progressBar_4.setValue(0)
        self.progressBar_4.setTextVisible(True)
        self.progressBar_4.setOrientation(Qt.Orientation.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.label_3 = QLabel(self.page_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 140, 161, 20))
        font3 = QFont()
        font3.setItalic(True)
        self.label_3.setFont(font3)
        self.label_4 = QLabel(self.page_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(180, 230, 161, 20))
        self.label_4.setFont(font3)
        self.label_5 = QLabel(self.page_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 320, 161, 20))
        self.label_5.setFont(font3)
        self.label_13 = QLabel(self.page_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(180, 410, 161, 20))
        self.label_13.setFont(font3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_18 = QLabel(self.page_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 10, 413, 20))
        self.label_18.setFont(font)
        self.label_22 = QLabel(self.page_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 40, 141, 20))
        font4 = QFont()
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setItalic(True)
        self.label_22.setFont(font4)
        self.label_26 = QLabel(self.page_4)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 80, 141, 20))
        self.label_26.setFont(font4)
        self.label_27 = QLabel(self.page_4)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 120, 141, 20))
        self.label_27.setFont(font4)
        self.label_28 = QLabel(self.page_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 160, 141, 20))
        self.label_28.setFont(font4)
        self.label_35 = QLabel(self.page_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(460, 30, 211, 20))
        self.label_35.setFont(font4)
        self.pushButton_9 = QPushButton(self.page_4)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(580, 500, 161, 61))
        self.pushButton_10 = QPushButton(self.page_4)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(230, 500, 291, 61))
        self.pushButton_11 = QPushButton(self.page_4)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(30, 500, 161, 61))
        self.verticalLayoutWidget_2 = QWidget(self.page_4)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(150, 200, 471, 291))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_34 = QLabel(self.verticalLayoutWidget_2)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setFrameShape(QFrame.Shape.NoFrame)
        self.label_34.setLineWidth(1)
        self.label_34.setScaledContents(True)

        self.verticalLayout_2.addWidget(self.label_34)

        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(170, 40, 101, 20))
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(False)
        font5.setItalic(True)
        self.label_36.setFont(font5)
        self.label_37 = QLabel(self.page_4)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(170, 80, 101, 20))
        self.label_37.setFont(font5)
        self.label_38 = QLabel(self.page_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(170, 120, 101, 20))
        self.label_38.setFont(font5)
        self.label_39 = QLabel(self.page_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(170, 160, 101, 20))
        self.label_39.setFont(font5)
        self.label_43 = QLabel(self.page_4)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(550, 60, 61, 41))
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(False)
        font6.setItalic(False)
        self.label_43.setFont(font6)
        self.label_43.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_44 = QLabel(self.page_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(550, 120, 61, 41))
        self.label_44.setFont(font6)
        self.label_44.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_45 = QLabel(self.page_4)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(470, 120, 61, 41))
        self.label_45.setFont(font6)
        self.label_45.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_46 = QLabel(self.page_4)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(470, 60, 61, 41))
        self.label_46.setFont(font6)
        self.label_46.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line = QFrame(self.page_4)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(530, 60, 20, 111))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.page_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(480, 110, 118, 3))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.page_4)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-80, 180, 901, 20))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow) -> None:
        """
        Adding text in appropriate objects (Translated if needed).

        Args:


        Returns:
        :return: None
        """
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Neural Network Trainer", None))
        self.label_2.setText("")
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"LOAD DATA", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"NEXT STEP", None))
        self.label.setText(
            QCoreApplication.translate("MainWindow", u"Load path to directory containing data to train neural network.",
                                       None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Customize hyperparameters.", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"NEXT STEP", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"PREVIOUS STEP", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"1. Layer - Input Layer", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"2. Layer - Normalization Layer", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"3. Layer - Dense Layer", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Neurons:", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Activation method:", None))

        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Exponential Linear Unit", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Hard Sigmoidal", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Rectified Linear Uni", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Sigmoidal", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"Softmax", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"Swish", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"Tanh", None))

        self.label_14.setText(QCoreApplication.translate("MainWindow",
                                                         u"4. Layer - Parametric Rectified Linear Unit Activation ("
                                                         u"PReLU) - Optional",
                                                         None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Use PReLU", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"5. Layer - Dense Layer", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Neurons:", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Activation method:", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Exponential Linear Unit", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Hard Sigmoidal", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Rectified Linear Uni", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"Sigmoidal", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("MainWindow", u"Softmax", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("MainWindow", u"Swish", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("MainWindow", u"Tanh", None))

        self.label_19.setText(QCoreApplication.translate("MainWindow", u"6. Layer - Dense Layer", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Neurons:", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Activation method:", None))

        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Exponential Linear Unit", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"Hard Sigmoidal", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"Rectified Linear Uni", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", u"Sigmoidal", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", u"Softmax", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("MainWindow", u"Swish", None))
        self.comboBox_3.setItemText(6, QCoreApplication.translate("MainWindow", u"Tanh", None))

        self.label_23.setText(QCoreApplication.translate("MainWindow", u"7. Layer - Output Layer", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Neurons:", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Activation method:", None))

        self.comboBox_4.setItemText(0, QCoreApplication.translate("MainWindow", u"Exponential Linear Unit", None))
        self.comboBox_4.setItemText(1, QCoreApplication.translate("MainWindow", u"Hard Sigmoidal", None))
        self.comboBox_4.setItemText(2, QCoreApplication.translate("MainWindow", u"Rectified Linear Uni", None))
        self.comboBox_4.setItemText(3, QCoreApplication.translate("MainWindow", u"Sigmoidal", None))
        self.comboBox_4.setItemText(4, QCoreApplication.translate("MainWindow", u"Softmax", None))
        self.comboBox_4.setItemText(5, QCoreApplication.translate("MainWindow", u"Swish", None))
        self.comboBox_4.setItemText(6, QCoreApplication.translate("MainWindow", u"Tanh", None))

        self.label_29.setText(QCoreApplication.translate("MainWindow", u"L2 regularizer \u03bb:", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"L2 regularizer \u03bb:", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"L2 regularizer \u03bb:", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"L2 regularizer \u03bb:", None))
        self.label_7.setText(
            QCoreApplication.translate("MainWindow", u"Train your created model and see the results.", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"PREVIOUS STEP", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"TRAIN MODEL", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Fitting last data...", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Testing the model...", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Generating results...", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Visualizing results...", None))
        self.label_18.setText(
            QCoreApplication.translate("MainWindow", u"Results of your neural network classifier.", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"ACCURACY:", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"PRECISION:", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"F1-SCORE:", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"RECALL:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"CONFUSION MATRIX:", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"EXIT", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"MODIFY HYPERPARAMETERS", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"CHANGE DATASET", None))
        self.label_34.setText("")
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"99.99%", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"99.99%", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"99.99%", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"99.99%", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"9999", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"9999", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"9999", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"9999", None))
